version: '2'
services:
  api:
    image: dougnd/openeats-api
    container_name: df_oe_api
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    env_file:
      env_prod.list
  node:
    image: openeats/openeats-web
    container_name: df_oe_node
    command: yarn start
    depends_on:
      - api
    volumes:
      - public-ui:/code/build
    env_file:
      env_prod.list
  db:
    image: mariadb
    container_name: df_db
    env_file:
      env_prod.list
  nginx:
    build: services/
    container_name: df_nginx
    command: ./start.sh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
      - public-ui:/var/www/html/openeats-static/public-ui
      - /root/research/vtdoc:/var/www/html/research/vtdoc
      - /root/OutOfArtifice-staging/public:/var/www/html/OutOfArtifice-staging
      - /var/www/letsencrypt:/var/www/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - node
      - fathom
    env_file:
      env_prod.list
  fathom:
    image: usefathom/fathom:latest
    container_name: df_fathom
    env_file:
      env_prod.list
    volumes:
      - fathom-db:/var/fathom-db

volumes:
  database:
  static-files:
  site-media:
  public-ui:
  fathom-db:
