version: '2'
services:
  api:
    image: dougnd/openeats-api
    container_name: df_oe_api
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    env_file:
      env_prod.list
  node:
    image: dougnd/openeats-node
    container_name: df_oe_node
    command: npm start
    depends_on:
      - api
    env_file:
      env_prod.list
  db:
    image: mariadb
    container_name: df_db
    env_file:
      env_prod.list
  nginx:
    build: services/
    container_name: df_nginx
    command: ./start.sh
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
      - /var/www/letsencrypt:/var/www/letsencrypt
    depends_on:
      - api
      - node
    env_file:
      env_prod.list
volumes:
  database:
  static-files:
  site-media:
